### ISSUE TITLE
Cannot find native module 'ExpoKioskControl'

### ISSUE THREAD

**Issue by bladerunner2020** [TheNinza/expo-kiosk-control#1]
Tried to install expo-kiosk-control, but got error: `Cannot find native module 'ExpoKioskControl` when running my app. I believe there should be additional steps to say expo to install native module during prebuild.

Could you help?

**Comment by bladerunner2020** [comment]
Fixed it by removing android folder and running again.

**Comment by khadijagougou** [comment]
I removed the android folder, but I'm still getting the same error.
